# Python application test with Github actions

name: CI

# Controls when the workflow will run
on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: install dependencies  
      run: | 
        make install
    - name: Lint with pylint
      run: make lint
    - name: Test with pyteste
      run: make test
    
